export { default as Categories } from './categories'
export { default as Products } from './products'
export { default as Detail } from './detail'
export { default as Orders } from './orders'
export { default as Cart } from './cart'